### PR TITLE
Feature add: the bot will delete the musicard/player message when track ends

### PR DESCRIPTION
**Pull request by BebanCode**
image
^^
**The bot will delete the player message + button instead of disabling it**

### CODE REVIEW

**Comment by UnschooledGamer** [comment]
@Elitex07, do you Need this in this Repo? I wanted to keep it simple as it represents **Riffy's** ability.

**Review by Ramkrishna-0 — APPROVED** [review]
Nice

**Review by Elitex07 — APPROVED** [review]
Certainly, a better way of handling the player message.

**Comment by BebanCode** [comment]
# Yay 🥳

**Pull request merged**
